#### 2024-12-27

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------------- ---------------------- 5.5/12.6 MB 28.8 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 30.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 26.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [8]:
np.__version__

'2.2.1'

In [9]:
a_list = [1,2,3,4]
a_list

[1, 2, 3, 4]

In [10]:
type(a_list)

list

In [11]:
int_arr = np.array([1,2,3,4])
int_arr

array([1, 2, 3, 4])

In [12]:
print(int_arr)

[1 2 3 4]


In [13]:
type(int_arr)

numpy.ndarray

In [17]:
list_data = [1,2.2,3, '4', [1,2]]


arr = np.array(list_data)

print(arr)
print(type(arr))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [19]:
arr1 = np.arange(1, 10, 2)

arr1

array([1, 3, 5, 7, 9])

In [23]:
arr = np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
arr = np.array([[1,2,3,4,], [5,6,7,8],[9,10,11,12]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [28]:
arr = np.array([[[1,2,3,4,], [5,6,7,8]],
[[9,10,11,12], [13,14,15,16]],
[[9,10,11,12], [13,14,15,16]]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
(3, 2, 4)


In [26]:
int_arr = np.array([1,2,3,4])
print(int_arr)
print(int_arr.ndim)
print(int_arr.shape)

[1 2 3 4]
1
(4,)


In [37]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr.reshape(2,6)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [39]:
a = [1,2,3]
b = [4,5,6]

print(type(a), type(b))

print(a + b)
print(a * 3)


<class 'list'> <class 'list'>
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(type(a), type(b))

print(a + b)
a * b

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[5 7 9]


array([ 4, 10, 18])

In [53]:
data = [0,1,2,3,4,5,6,7,8,9]

for i in data:
    data2 = []
    data2.append(2 * i)
    print(data2)

[0]
[2]
[4]
[6]
[8]
[10]
[12]
[14]
[16]
[18]


In [54]:
x =np.array(data)
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
c = np.array([[0,1,2], [3,4,5]])
print(len(c), len(c[0]))

2 3


In [60]:
a = np.array([0,1,2,3,4,])

print(a[2])
print(a[-1])

2
4


In [63]:
a = np.array([[0,1,2], [3,4,5]])
print(a[0,0])
print(a[0,1])
print(a[-1,-1])

0
1
5


In [85]:
b = np.array([[0,1,2,3], [4,5,6,7]])

print(b[0, :])
print(b[:, 1])
print(b[1, 1:])
print(b[:2, :2])

[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [90]:
a = np.array([1,2,3,])
b = np.array([10,20,30])

print(2 * a + b)
print(a == 2)
print(b > 10)
(a == 2) & (b > 10)

[12 24 36]
[False  True False]
[False  True  True]


array([False,  True, False])

In [93]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

idx = np.array([True, False, True, False, True,
 False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [99]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

a % 2 == 0

a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [100]:
a[a > 4]

array([5, 6, 7, 8, 9])

In [104]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0,2,3,4,6,8])
#팬시 인덱싱에선 idx가 인덱싱 번호가 되어버림

a[idx] #인덱스 번호로 필터링

array([11, 33, 44, 55, 77, 99])

In [106]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0,0,0,1,1,1,1,2,2,2,5,5,5,5])

a[idx]

array([11, 11, 11, 22, 22, 22, 22, 33, 33, 33, 66, 66, 66, 66])

In [114]:
a = np.array([[1,2,3,4,], [5,6,7,8,], [9,10,11,12]])


a[:, [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [117]:
a = np.array([[1,2,3,4,], [5,6,7,8,], [9,10,11,12]])
idx = np.array([2,0,1])

a[idx]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [118]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [124]:
x = np.array([1, 2, 3,4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
 
# 배열에서 3의 배수를 찾아주세요.
 
# 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
 
# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.

print(x[x % 3 ==0])
print(x[x % 4 ==1])
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


#### 판다스

In [359]:
pip install pandas

In [360]:
import pandas as pd

In [361]:
pd.__version__

'2.2.3'

In [362]:
s = pd.Series([3,-5,7,4])
print(s)
print(type(s))

0    3
1   -5
2    7
3    4
dtype: int64
<class 'pandas.core.series.Series'>


In [363]:
s = pd.Series([3,-5,7,4], index=['a','b','c','d'])
print(s)
print(type(s))

a    3
b   -5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [364]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [365]:
s.values

array([ 3, -5,  7,  4])

In [366]:
print(s[0])

3


C:\Users\USER\AppData\Local\Temp\ipykernel_4700\287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [367]:
print(s['a'])

3


In [368]:
s

a    3
b   -5
c    7
d    4
dtype: int64

In [369]:
s * 3

a     9
b   -15
c    21
d    12
dtype: int64

In [370]:
df = pd.DataFrame({'Division':['부산광역시',' 전라남도', '강원도'],
                   'Code':['051', '061', '033'],
                   'Population':[3364358, 1840921, 1535530]})

display(df)

Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

In [371]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [372]:
print(df)

  Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530


In [373]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [374]:
df.columns

Index(['Division', 'Code', 'Population'], dtype='object')

In [375]:
df.values

array([['부산광역시', '051', 3364358],
       [' 전라남도', '061', 1840921],
       ['강원도', '033', 1535530]], dtype=object)

In [376]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [377]:
df.set_index('Division')

Code  Population
Division                 
부산광역시     051     3364358
 전라남도     061     1840921
강원도       033     1535530

In [487]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [488]:
pd.options.display.float_format = '{:.0f}'.format

In [489]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [490]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [491]:
df.head()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [492]:
df.tail()

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [493]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [494]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [495]:
df['나이'].value_counts()

나이
58    1
45    1
18    1
27    1
33    1
25    1
32    1
Name: count, dtype: int64

In [496]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [497]:
df['재산'].nsmallest()

2           600
6      50000000
5     340000000
4    1000000000
0   11500000000
Name: 재산, dtype: float64

In [498]:
df.nlargest(3, '나이')

이름  나이     직업     국적    키          재산
0  아이언맨  58    CEO     미국  174 11500000000
1    토르  45      신  아스가르드  190         NaN
4    헐크  33  핵물리학자     미국  270  1000000000

In [499]:
df.nsmallest(5, '재산')

이름  나이     직업   국적    키          재산
2  스파이더맨  18   고등학생   미국  177         600
6  블랙위도우  32    스파이  러시아  170    50000000
5   캡틴마블  25    파일럿   미국  170   340000000
4     헐크  33  핵물리학자   미국  270  1000000000
0   아이언맨  58    CEO   미국  174 11500000000

In [500]:
df[['이름', '재산']]

이름          재산
0   아이언맨 11500000000
1     토르         NaN
2  스파이더맨         600
3   원더우먼         NaN
4     헐크  1000000000
5   캡틴마블   340000000
6  블랙위도우    50000000

In [501]:
df['이름'][1:5]

1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [502]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [503]:
df.iloc[0:7, 0]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
5     캡틴마블
6    블랙위도우
Name: 이름, dtype: object

In [504]:
df.iloc[[1,3,4],[1,2,3,4]]

나이     직업     국적    키
1  45      신  아스가르드  190
3  27     공주  데미스키라  178
4  33  핵물리학자     미국  270

In [505]:
df.iloc[0,0]

'아이언맨'

In [506]:
df.iloc[:5,:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [507]:
df2 = df.copy()

df2.index = ['a','b','c','d','e','f','g']

df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [508]:
df2.loc['a':'b']

이름  나이   직업     국적    키          재산
a  아이언맨  58  CEO     미국  174 11500000000
b    토르  45    신  아스가르드  190         NaN

In [509]:
df2.loc['a', '이름']

'아이언맨'

In [510]:
df2.loc['a':'c', '이름':'국적']

이름  나이    직업     국적
a   아이언맨  58   CEO     미국
b     토르  45     신  아스가르드
c  스파이더맨  18  고등학생     미국

In [511]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, a to g
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 692.0+ bytes


In [512]:
df2['재산'].isnull()

a    False
b     True
c    False
d     True
e    False
f    False
g    False
Name: 재산, dtype: bool

In [513]:
df2[df2['재산'].isnull()]

이름  나이  직업     국적    키  재산
b    토르  45   신  아스가르드  190 NaN
d  원더우먼  27  공주  데미스키라  178 NaN

In [514]:
df2.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [515]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [516]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [517]:
df.loc[(df['나이'] > 30) & (df['나이'] < 50), ['이름','나이','직업']]

이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [518]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [519]:
filtered_df = df[(df['나이'] > 30) & (df['나이'] < 50)]
result = filtered_df.iloc[:, [0, 1, 2]]

print(result)

      이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이


In [520]:
df_a = df.sort_values('키')
df_a

이름  나이     직업     국적    키          재산
6  블랙위도우  32    스파이    러시아  170    50000000
5   캡틴마블  25    파일럿     미국  170   340000000
0   아이언맨  58    CEO     미국  174 11500000000
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [521]:
df.sort_values('재산', ascending=True) #오름차순, 내림차순은 False

이름  나이     직업     국적    키          재산
2  스파이더맨  18   고등학생     미국  177         600
6  블랙위도우  32    스파이    러시아  170    50000000
5   캡틴마블  25    파일럿     미국  170   340000000
4     헐크  33  핵물리학자     미국  270  1000000000
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN

In [522]:
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [523]:
df2['국적'] = '대한민국'
df2

이름  나이     직업    국적    키          재산
a   아이언맨  58    CEO  대한민국  174 11500000000
b     토르  45      신  대한민국  190         NaN
c  스파이더맨  18   고등학생  대한민국  177         600
d   원더우먼  27     공주  대한민국  178         NaN
e     헐크  33  핵물리학자  대한민국  270  1000000000
f   캡틴마블  25    파일럿  대한민국  170   340000000
g  블랙위도우  32    스파이  대한민국  170    50000000

In [524]:
df2['전투력'] = [91, 95, 100, 90, 94, 5, 87]

In [525]:
df2['전투력'] = df2['전투력'] - 5
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   86
b     토르  45      신  대한민국  190         NaN   90
c  스파이더맨  18   고등학생  대한민국  177         600   95
d   원더우먼  27     공주  대한민국  178         NaN   85
e     헐크  33  핵물리학자  대한민국  270  1000000000   89
f   캡틴마블  25    파일럿  대한민국  170   340000000    0
g  블랙위도우  32    스파이  대한민국  170    50000000   82

In [526]:
df2.columns = ['성명','연령','하는일','출신국가','신장','재산현황','파워']
df2

성명  연령    하는일  출신국가   신장        재산현황  파워
a   아이언맨  58    CEO  대한민국  174 11500000000  86
b     토르  45      신  대한민국  190         NaN  90
c  스파이더맨  18   고등학생  대한민국  177         600  95
d   원더우먼  27     공주  대한민국  178         NaN  85
e     헐크  33  핵물리학자  대한민국  270  1000000000  89
f   캡틴마블  25    파일럿  대한민국  170   340000000   0
g  블랙위도우  32    스파이  대한민국  170    50000000  82

In [527]:
name_changes = { '아이언맨': '강철남자', 
                '토르': '번개인간', 
                '스파이더맨': '거미남자', 
                '원더우먼': '짱쎈여자', 
                '헐크': '녹색괴물', 
                '캡틴마블': '응가', 
                '블랙위도우': '검은요원' }
df2['성명'] = df2['성명'].replace(name_changes)

df2

성명  연령    하는일  출신국가   신장        재산현황  파워
a  강철남자  58    CEO  대한민국  174 11500000000  86
b  번개인간  45      신  대한민국  190         NaN  90
c  거미남자  18   고등학생  대한민국  177         600  95
d  짱쎈여자  27     공주  대한민국  178         NaN  85
e  녹색괴물  33  핵물리학자  대한민국  270  1000000000  89
f    응가  25    파일럿  대한민국  170   340000000   0
g  검은요원  32    스파이  대한민국  170    50000000  82

In [528]:
df2.drop(index=['a'], inplace=True)

In [529]:
df2.drop(columns=['신장'], inplace=True)

In [530]:
df2

성명  연령    하는일  출신국가       재산현황  파워
b  번개인간  45      신  대한민국        NaN  90
c  거미남자  18   고등학생  대한민국        600  95
d  짱쎈여자  27     공주  대한민국        NaN  85
e  녹색괴물  33  핵물리학자  대한민국 1000000000  89
f    응가  25    파일럿  대한민국  340000000   0
g  검은요원  32    스파이  대한민국   50000000  82

In [531]:
df2.dropna()

성명  연령    하는일  출신국가       재산현황  파워
c  거미남자  18   고등학생  대한민국        600  95
e  녹색괴물  33  핵물리학자  대한민국 1000000000  89
f    응가  25    파일럿  대한민국  340000000   0
g  검은요원  32    스파이  대한민국   50000000  82

In [533]:
df2.dropna(axis=1)

성명  연령    하는일  출신국가  파워
b  번개인간  45      신  대한민국  90
c  거미남자  18   고등학생  대한민국  95
d  짱쎈여자  27     공주  대한민국  85
e  녹색괴물  33  핵물리학자  대한민국  89
f    응가  25    파일럿  대한민국   0
g  검은요원  32    스파이  대한민국  82

In [534]:
df2

성명  연령    하는일  출신국가       재산현황  파워
b  번개인간  45      신  대한민국        NaN  90
c  거미남자  18   고등학생  대한민국        600  95
d  짱쎈여자  27     공주  대한민국        NaN  85
e  녹색괴물  33  핵물리학자  대한민국 1000000000  89
f    응가  25    파일럿  대한민국  340000000   0
g  검은요원  32    스파이  대한민국   50000000  82

In [537]:
df2.fillna('거지')

성명  연령    하는일  출신국가       재산현황  파워
b  번개인간  45      신  대한민국         거지  90
c  거미남자  18   고등학생  대한민국        600  95
d  짱쎈여자  27     공주  대한민국         거지  85
e  녹색괴물  33  핵물리학자  대한민국 1000000000  89
f    응가  25    파일럿  대한민국  340000000   0
g  검은요원  32    스파이  대한민국   50000000  82

In [538]:
df2['재산현황'].mean()

np.float64(347500150.0)

In [539]:
df2.fillna(df2['재산현황'].mean())

성명  연령    하는일  출신국가       재산현황  파워
b  번개인간  45      신  대한민국  347500150  90
c  거미남자  18   고등학생  대한민국        600  95
d  짱쎈여자  27     공주  대한민국  347500150  85
e  녹색괴물  33  핵물리학자  대한민국 1000000000  89
f    응가  25    파일럿  대한민국  340000000   0
g  검은요원  32    스파이  대한민국   50000000  82

In [559]:
df2['출신국가'] = '남한'

df2

성명  연령    하는일 출신국가       재산현황  파워 (출신국가, 4)
b   번개인간  45      신   남한        NaN  90        북한
c   거미남자  18   고등학생   남한        600  95        북한
d   짱쎈여자  27     공주   남한        NaN  85        북한
e   녹색괴물  33  핵물리학자   남한 1000000000  89        북한
f  미국대장장  25    파일럿   남한  340000000   0        북한
g   검은요원  32    스파이   남한   50000000  82        북한

In [560]:
df2.loc[df2['성명'] == '응가', '출신국가'] = '북한'
df2.loc[df2['성명'] == '응가', '성명'] = '미국대장'

df2

성명  연령    하는일 출신국가       재산현황  파워 (출신국가, 4)
b   번개인간  45      신   남한        NaN  90        북한
c   거미남자  18   고등학생   남한        600  95        북한
d   짱쎈여자  27     공주   남한        NaN  85        북한
e   녹색괴물  33  핵물리학자   남한 1000000000  89        북한
f  미국대장장  25    파일럿   남한  340000000   0        북한
g   검은요원  32    스파이   남한   50000000  82        북한